import assert from 'node:assert/strict';
import { RoomService, parseInput } from '../realtime/room-service.js';
import { SHARED_LAKE_RULES } from '../simulation/defaults.js';
import { STALE_MS } from '../multiplayer/room.js';

const base = 100000, room = new RoomService('test-room');
const a = { id: 'player-00000000001', token: 'secret-00000000000000000000000001', physicsVersion: SHARED_LAKE_RULES.version };
const b = { ...a, id: 'player-00000000002' };
const join = (session, at = base) => room.action({ ...session, action: 'join', botCount: 1 }, session.id, at);
const first = join(a), second = join(b);
assert.equal(first.resumed, false); assert.equal(second.players.filter(p => !p.isBot).length, 2);
const p = room.room.players[a.id], pose = { ...p.boat };
room.action({ ...a, action: 'sync', seq: 1, ack: 0, boat: pose, tube: p.tube, paused: false, botCount: 1 }, a.id, base + 100);
const before = structuredClone(room.room);
assert.throws(() => room.action({ ...a, action: 'sync', seq: 99, boat: { x: 'bad' }, tube: p.tube }, a.id, base + 110));
assert.deepEqual(room.room, before, 'Rejected input must not mutate the live room');
assert.throws(() => room.action({ ...a, action: 'join' }, 'wrong-owner', base + 120));
assert.deepEqual(room.room, before, 'Wrong ownership must not change room membership');
const resume = join(a, base + 200);
assert.equal(resume.resumed, true); assert.deepEqual(room.room.players[a.id].boat, before.players[a.id].boat);

const botBefore = structuredClone(Object.values(room.room.players).find(p => p.isBot));
room.tick(base + 2100);
const botAfter = room.room.players[botBefore.id];
assert.ok(botAfter.poseAt > botBefore.poseAt, 'Bots advance on the room clock without client messages');
assert.notDeepEqual(botAfter.boat, botBefore.boat);
room.room.players[a.id].correction = { seq: 1, dx: 1, dy: 0, dvx: 2, dvy: 0 };
room.room.players[b.id].correction = { seq: 2, dx: -1, dy: 0, dvx: -2, dvy: 0 };
room.room.wakeEvents = [[1, base + 2000, 0, 0, 0, 50], [2, base + 2100, 0, 0, 0, 50]];
room.room.wakeSeq = 2;
const viewA = room.view(a.id, a.id, 1, base + 2200), viewB = room.view(b.id, b.id, 0, base + 2200);
assert.equal(viewA.self.correction.seq, 1); assert.equal(viewB.self.correction.seq, 2);
assert.deepEqual(viewA.wakeEvents.map(e => e[0]), [2]); assert.equal(viewB.wakeEvents.length, 2);
assert.ok(!JSON.stringify(viewA).includes('tokenHash'), 'Snapshots never reveal ownership credentials');
room.tick(base + STALE_MS + 3000);
assert.equal(room.active, false); assert.equal(Object.keys(room.room.players).length, 0);
assert.equal(join(a, base + STALE_MS + 3100).resumed, false, 'Expired reservations get a new spawn even in the same actor');
assert.throws(() => parseInput('invalid')); assert.throws(() => parseInput('x'.repeat(6001)));
console.log('Realtime room passed: atomic rejection, ownership, personalized wakes/corrections, timed bots, resume and expiry.');
