export function createBoatState() {
  return {
    x: 0,
    y: 0,
    vx: 0,
    vy: 0,
    z: 0,
    vz: 0,
    pitch: 0,
    pitchRate: 0,
    roll: 0,
    rollRate: 0,
    air: false,
    impact: 0,
    splash: 0,
    shoreBounceTime: 0,
    bumpGlideTime: 0,
    bumpReverseCoast: false,
    contactFraction: 1,
    launchReadiness: 0,
    launchImpulse: 0,
    angle: -Math.PI / 2,
    speed: 0,
    lateralSpeed: 0,
    yawRate: 0,
    wheel: 0,
    towVerticalLoad: 0
  };
}

export function createTubeState(center, angle = -Math.PI / 2) {
  return {
    x: center.x,
    y: center.y,
    vx: 0,
    vy: 0,
    z: 0,
    vz: 0,
    prevVx: 0,
    prevVy: 0,
    prevVz: 0,
    angle,
    angularVelocity: 0,
    pitch: 0,
    pitchRate: 0,
    roll: 0,
    air: false,
    splash: 0,
    collisionCompression: 0,
    collisionGlideTime: 0,
    collisionCompressionVelocity: 0,
    collisionSplash: 0,
    collisionAge: 10,
    collisionImpactTime: 0,
    tension: 0,
    loadBaseline: 0,
    loadShock: 0,
    impact: 0,
    riderOn: true,
    riderReturn: 0,
    fallSplash: 0,
    fallenRider: null,
    feltG: 1,
    peakG: 1,
    contacts: null,
    debugAx: 0,
    debugAy: 0,
    debugAz: 0
  };
}
